apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: lvm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lvm-operator
    app.kubernetes.io/part-of: lvm-operator
  name: lvm-operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: lvm-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: lvm-operator
    spec:
      containers:
      - env:
        - name: GOGC
          value: "120"
        - name: GOMAXPROCS
          value: "2"
        - name: NAMESPACE
          value: openshift-storage
        - name: NAME
          value: lvms-operator
        image: quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvm-operator/lvm-operator@sha256:51773333ef4e3da1833eb2ece888bc09a49a2a3d6b5608bfcb63347b9bc9eaa2
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 5m
            memory: 50Mi
status: {}
