apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: lvm-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvm-operator/lvm-operator@sha256:d2717bc0b8cefe9dd89e1396e233221aa80e71eee47a381299e1ee1884e131a1
        name: container-image
        resources: {}
status: {}
